/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Paleta Oficial Accesorios Bunu Shop (Femenina, Artesanal, Elegante)
        brand: {
          pink: '#db2777',
          pinkHover: '#be185d',
          pinkLight: '#fdf2f8',
          lavender: '#c084fc',
          lavenderLight: '#faf5ff',
          lavenderDark: '#7e22ce',
          gold: '#f59e0b',
          goldLight: '#fef3c7',
          darkNavy: '#2e1065', // Ciruela profundo / Morado imperial
          deepSlate: '#1e0836',
          slateBlue: '#4c1d95',
          mutedGray: '#705e78',
          lightBg: '#fdf7f9',
          borderLight: '#fce7f3',
          accentLight: '#ffe4e6',
          // Aliases para componentes existentes
          coral: '#ec4899',
          coralHover: '#db2777',
          coralLight: '#fdf2f8',
        },
        // Editorial Studio / CMS Admin Colors ajustados a la marca Bunu Shop
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#831843',
        error: '#ba1a1a',
        'on-secondary-container': '#581c87',
        background: '#fdf7f9',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2e1065',
        outline: '#9d8189',
        'on-secondary-fixed-variant': '#4c1d95',
        'outline-variant': '#fce7f3',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#fbcfe8',
        'surface-container-highest': '#f5d0fe',
        secondary: '#705e78',
        'surface-tint': '#ec4899',
        'secondary-fixed': '#fae8ff',
        'on-tertiary-fixed': '#451a03',
        'primary-container': '#db2777',
        tertiary: '#b45309',
        'on-primary-container': '#ffffff',
        primary: '#ec4899',
        'surface-variant': '#fdf2f8',
        'surface-dim': '#f5e8ed',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#fde68a',
        'on-tertiary-fixed-variant': '#78350f',
        'secondary-container': '#f3e8ff',
        'surface-container-low': '#fff1f2',
        'inverse-primary': '#f472b6',
        'on-secondary-fixed': '#3b0764',
        'on-tertiary': '#ffffff',
        'on-background': '#2e1065',
        'secondary-fixed-dim': '#e9d5ff',
        'surface-container-high': '#fce7f3',
        'on-tertiary-container': '#ffffff',
        'surface-bright': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#fef3c7',
        surface: '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#fdf2f8',
        'primary-fixed': '#fce7f3',
        'on-primary-fixed': '#500724',
        'on-surface-variant': '#705e78',
        'tertiary-container': '#d97706',
        'inverse-on-surface': '#fdf4f8',
        'on-surface': '#2e1065',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Outfit"', 'sans-serif'],
        code: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'fluid-h1-mobile': 'clamp(1.5rem, 1.125rem + 1.875vw, 1.875rem)',
        'fluid-h2': 'clamp(1.875rem, 1.5rem + 1.875vw, 3rem)',
        'fluid-h2-sm': 'clamp(1.875rem, 1.75rem + 0.625vw, 2.25rem)',
        'fluid-h3': 'clamp(1.5rem, 1.25rem + 1.25vw, 2.25rem)',
        'fluid-body': 'clamp(0.875rem, 0.8333rem + 0.2083vw, 1rem)',
        'fluid-body-sm': 'clamp(0.75rem, 0.7083rem + 0.2083vw, 0.875rem)',
      },
    },
  },
  plugins: [forms],
};
